<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220601133415 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE planificacion.plan_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE plan_actividades.tbd_actividad_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE personal.tbd_datos_fuc_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE estructura.tbd_entidad_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE estructura.tbd_estructura_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE seguridad.tbd_funcionalidad_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE seguridad.tbd_modulo_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE plan_actividades.tbd_nota_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE personal.tbd_persona_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE personal.tbd_plantilla_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE seguridad.tbd_rol_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE plan_actividades.tbd_todo_lista_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE seguridad.tbd_usuario_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE personal.tbn_carrera_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE personal.tbn_categoria_docente_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE estructura.tbn_categoria_estructura_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE personal.tbn_categoria_investigativa_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE estructura.tbn_categoria_responsabilidad_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE personal.tbn_clasificacion_persona_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE plan_actividades.tbn_estado_actividad_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE personal.tbn_grado_academico_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE estructura.tbn_municipio_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE estructura.tbn_nivel_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE personal.tbn_nivel_escolar_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE personal.tbn_organizacion_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE personal.tbn_profesion_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE estructura.tbn_provincia_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE estructura.tbn_responsabilidad_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE personal.tbn_sexo_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE plan_actividades.tbn_tipo_actividad_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE estructura.tbn_tipo_entidad_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE estructura.tbn_tipo_estructura_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE personal.tbn_tipo_organizacion_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE personal.tbr_persona_organizacion_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE estructura.tbr_plaza_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE planificacion.plan (id INT NOT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE plan_actividades.tbd_actividad (id INT NOT NULL, tipo_actividad_id INT NOT NULL, estado_actividad_id INT NOT NULL, nombre VARCHAR(250) NOT NULL, descripcion TEXT DEFAULT NULL, fecha_inicio DATE NOT NULL, hora_inicio TIME(0) WITHOUT TIME ZONE DEFAULT NULL, fecha_fin DATE NOT NULL, fecha_cumplimiento DATE DEFAULT NULL, porciento_cumplimiento INT DEFAULT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_616066AED347A4CA ON plan_actividades.tbd_actividad (tipo_actividad_id)');
        $this->addSql('CREATE INDEX IDX_616066AEB45A7D7 ON plan_actividades.tbd_actividad (estado_actividad_id)');
        $this->addSql('CREATE TABLE plan_actividades.tbr_responsable (persona_id INT NOT NULL, actividad_id INT NOT NULL, PRIMARY KEY(persona_id, actividad_id))');
        $this->addSql('CREATE INDEX IDX_316FA52FF5F88DB9 ON plan_actividades.tbr_responsable (persona_id)');
        $this->addSql('CREATE INDEX IDX_316FA52F6014FACA ON plan_actividades.tbr_responsable (actividad_id)');
        $this->addSql('CREATE TABLE personal.tbd_datos_fuc (id INT NOT NULL, id_fuc VARCHAR(255) NOT NULL, carnet_identidad VARCHAR(255) NOT NULL, nombre_completo VARCHAR(255) NOT NULL, fecha_nacimiento VARCHAR(255) DEFAULT NULL, codigo_sexo VARCHAR(255) DEFAULT NULL, codido_provincia VARCHAR(255) DEFAULT NULL, codido_municipio VARCHAR(255) DEFAULT NULL, direccion TEXT DEFAULT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CB31DB83AB4C3B8B ON personal.tbd_datos_fuc (id_fuc)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CB31DB83327C5C8A ON personal.tbd_datos_fuc (carnet_identidad)');
        $this->addSql('CREATE TABLE estructura.tbd_entidad (id INT NOT NULL, estructura_id INT DEFAULT NULL, tipo_entidad_id INT NOT NULL, municipio_id INT NOT NULL, provincia_id INT NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN NOT NULL, email VARCHAR(180) NOT NULL, telefono VARCHAR(15) NOT NULL, direccion TEXT NOT NULL, codigo TEXT NOT NULL, siglas TEXT NOT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AB79ADA6CD2B7E7C ON estructura.tbd_entidad (estructura_id)');
        $this->addSql('CREATE INDEX IDX_AB79ADA6FD2406C7 ON estructura.tbd_entidad (tipo_entidad_id)');
        $this->addSql('CREATE INDEX IDX_AB79ADA658BC1BE0 ON estructura.tbd_entidad (municipio_id)');
        $this->addSql('CREATE INDEX IDX_AB79ADA64E7121AF ON estructura.tbd_entidad (provincia_id)');
        $this->addSql('CREATE TABLE estructura.tbd_estructura (id INT NOT NULL, tipo_estructura_id INT DEFAULT NULL, estructura_id INT DEFAULT NULL, provincia_id INT DEFAULT NULL, municipio_id INT DEFAULT NULL, categoria_estructura_id INT DEFAULT NULL, nivel_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, siglas VARCHAR(15) NOT NULL, activo BOOLEAN NOT NULL, fecha_activacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ubicacion VARCHAR(255) DEFAULT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BF47AB85CD982D22 ON estructura.tbd_estructura (tipo_estructura_id)');
        $this->addSql('CREATE INDEX IDX_BF47AB85CD2B7E7C ON estructura.tbd_estructura (estructura_id)');
        $this->addSql('CREATE INDEX IDX_BF47AB854E7121AF ON estructura.tbd_estructura (provincia_id)');
        $this->addSql('CREATE INDEX IDX_BF47AB8558BC1BE0 ON estructura.tbd_estructura (municipio_id)');
        $this->addSql('CREATE INDEX IDX_BF47AB854498FA55 ON estructura.tbd_estructura (categoria_estructura_id)');
        $this->addSql('CREATE INDEX IDX_BF47AB85DA3426AE ON estructura.tbd_estructura (nivel_id)');
        $this->addSql('CREATE TABLE seguridad.tbd_funcionalidad (id INT NOT NULL, modulo_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, role_key VARCHAR(50) NOT NULL, activo BOOLEAN NOT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A72671893EF22FDB ON seguridad.tbd_funcionalidad (role_key)');
        $this->addSql('CREATE INDEX IDX_A7267189C07F55F5 ON seguridad.tbd_funcionalidad (modulo_id)');
        $this->addSql('CREATE TABLE seguridad.tbd_modulo (id INT NOT NULL, nombre VARCHAR(180) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN NOT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_285F9BC13A909126 ON seguridad.tbd_modulo (nombre)');
        $this->addSql('CREATE TABLE plan_actividades.tbd_nota (id INT NOT NULL, actividad_id INT NOT NULL, titulo VARCHAR(250) NOT NULL, mensaje TEXT DEFAULT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3A6B48AC6014FACA ON plan_actividades.tbd_nota (actividad_id)');
        $this->addSql('CREATE TABLE personal.tbd_persona (id INT NOT NULL, datos_fuc_id INT DEFAULT NULL, provincia_id INT DEFAULT NULL, municipio_id INT DEFAULT NULL, clasificacion_persona_id INT DEFAULT NULL, nivel_escolar_id INT DEFAULT NULL, categoria_docente_id INT DEFAULT NULL, profesion_id INT DEFAULT NULL, grado_academico_id INT DEFAULT NULL, categoria_investigativa_id INT DEFAULT NULL, carrera_id INT DEFAULT NULL, sexo_id INT DEFAULT NULL, categoria_estructura_id INT DEFAULT NULL, estructura_id INT DEFAULT NULL, responsabilidad_id INT DEFAULT NULL, usuario_id INT NOT NULL, activo BOOLEAN NOT NULL, carnet_identidad VARCHAR(11) NOT NULL, numero_serie_carnet_identidad VARCHAR(11) NOT NULL, primer_nombre VARCHAR(50) NOT NULL, segundo_nombre VARCHAR(50) DEFAULT NULL, primer_apellido VARCHAR(50) DEFAULT NULL, segundo_apellido VARCHAR(50) DEFAULT NULL, fecha_nacimiento TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, email VARCHAR(180) DEFAULT NULL, celular VARCHAR(15) DEFAULT NULL, telefono VARCHAR(15) DEFAULT NULL, direccion TEXT DEFAULT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D817A223327C5C8A ON personal.tbd_persona (carnet_identidad)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D817A223D1E70FBE ON personal.tbd_persona (numero_serie_carnet_identidad)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D817A22315ED7B6D ON personal.tbd_persona (datos_fuc_id)');
        $this->addSql('CREATE INDEX IDX_D817A2234E7121AF ON personal.tbd_persona (provincia_id)');
        $this->addSql('CREATE INDEX IDX_D817A22358BC1BE0 ON personal.tbd_persona (municipio_id)');
        $this->addSql('CREATE INDEX IDX_D817A223CF5FD27C ON personal.tbd_persona (clasificacion_persona_id)');
        $this->addSql('CREATE INDEX IDX_D817A2235873B5B9 ON personal.tbd_persona (nivel_escolar_id)');
        $this->addSql('CREATE INDEX IDX_D817A22392D84F6 ON personal.tbd_persona (categoria_docente_id)');
        $this->addSql('CREATE INDEX IDX_D817A223C5AF4D0F ON personal.tbd_persona (profesion_id)');
        $this->addSql('CREATE INDEX IDX_D817A2234683F2FA ON personal.tbd_persona (grado_academico_id)');
        $this->addSql('CREATE INDEX IDX_D817A223D3ECE4BD ON personal.tbd_persona (categoria_investigativa_id)');
        $this->addSql('CREATE INDEX IDX_D817A223C671B40F ON personal.tbd_persona (carrera_id)');
        $this->addSql('CREATE INDEX IDX_D817A2232B32DB58 ON personal.tbd_persona (sexo_id)');
        $this->addSql('CREATE INDEX IDX_D817A2234498FA55 ON personal.tbd_persona (categoria_estructura_id)');
        $this->addSql('CREATE INDEX IDX_D817A223CD2B7E7C ON personal.tbd_persona (estructura_id)');
        $this->addSql('CREATE INDEX IDX_D817A22396079139 ON personal.tbd_persona (responsabilidad_id)');
        $this->addSql('CREATE INDEX IDX_D817A223DB38439E ON personal.tbd_persona (usuario_id)');
        $this->addSql('CREATE TABLE personal.tbd_plantilla (id INT NOT NULL, persona_id INT NOT NULL, estructura_id INT NOT NULL, responsabilidad_id INT NOT NULL, id_expediente VARCHAR(36) NOT NULL, activo BOOLEAN NOT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_405B8B6CF5F88DB9 ON personal.tbd_plantilla (persona_id)');
        $this->addSql('CREATE INDEX IDX_405B8B6CCD2B7E7C ON personal.tbd_plantilla (estructura_id)');
        $this->addSql('CREATE INDEX IDX_405B8B6C96079139 ON personal.tbd_plantilla (responsabilidad_id)');
        $this->addSql('CREATE TABLE seguridad.tbd_rol (id INT NOT NULL, nombre VARCHAR(180) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN NOT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5F164513A909126 ON seguridad.tbd_rol (nombre)');
        $this->addSql('CREATE TABLE seguridad.tbr_rol_funcionalidad (rol_id INT NOT NULL, funcionalidad_id INT NOT NULL, PRIMARY KEY(rol_id, funcionalidad_id))');
        $this->addSql('CREATE INDEX IDX_5C2783B44BAB96C ON seguridad.tbr_rol_funcionalidad (rol_id)');
        $this->addSql('CREATE INDEX IDX_5C2783B43637E16E ON seguridad.tbr_rol_funcionalidad (funcionalidad_id)');
        $this->addSql('CREATE TABLE plan_actividades.tbd_todo_lista (id INT NOT NULL, usuario_id INT NOT NULL, nombre TEXT NOT NULL, fecha_cumplimiento DATE NOT NULL, terminado BOOLEAN NOT NULL, orden INT NOT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AE298B7FDB38439E ON plan_actividades.tbd_todo_lista (usuario_id)');
        $this->addSql('CREATE TABLE seguridad.tbd_usuario (id INT NOT NULL, persona_id INT DEFAULT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, role VARCHAR(255) NOT NULL, activo BOOLEAN NOT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_17879B6E7927C74 ON seguridad.tbd_usuario (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_17879B6F5F88DB9 ON seguridad.tbd_usuario (persona_id)');
        $this->addSql('CREATE TABLE seguridad.tbr_user_rol (user_id INT NOT NULL, rol_id INT NOT NULL, PRIMARY KEY(user_id, rol_id))');
        $this->addSql('CREATE INDEX IDX_F808892AA76ED395 ON seguridad.tbr_user_rol (user_id)');
        $this->addSql('CREATE INDEX IDX_F808892A4BAB96C ON seguridad.tbr_user_rol (rol_id)');
        $this->addSql('CREATE TABLE personal.tbn_carrera (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN NOT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE personal.tbn_categoria_docente (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN NOT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE estructura.tbn_categoria_estructura (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN NOT NULL, color VARCHAR(50) DEFAULT NULL, tributa_credencial BOOLEAN NOT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE personal.tbn_categoria_investigativa (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN NOT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE estructura.tbn_categoria_responsabilidad (id INT NOT NULL, categoria_responsabilidad_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN NOT NULL, color VARCHAR(50) DEFAULT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_39E2253E15B49E6B ON estructura.tbn_categoria_responsabilidad (categoria_responsabilidad_id)');
        $this->addSql('CREATE TABLE personal.tbn_clasificacion_persona (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN NOT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE plan_actividades.tbn_estado_actividad (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN NOT NULL, color VARCHAR(50) DEFAULT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE personal.tbn_grado_academico (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN NOT NULL, siglas VARCHAR(3) NOT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE estructura.tbn_municipio (id INT NOT NULL, provincia_id INT NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN NOT NULL, codigo INT NOT NULL, ext_id VARCHAR(255) DEFAULT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AF623AA94E7121AF ON estructura.tbn_municipio (provincia_id)');
        $this->addSql('CREATE TABLE estructura.tbn_nivel (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN NOT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE personal.tbn_nivel_escolar (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN NOT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE personal.tbn_organizacion (id INT NOT NULL, tipo_organizacion_id INT NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN NOT NULL, siglas VARCHAR(10) NOT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7DDAD16046EB71B9 ON personal.tbn_organizacion (tipo_organizacion_id)');
        $this->addSql('CREATE TABLE personal.tbn_profesion (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN NOT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE estructura.tbn_provincia (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN NOT NULL, codigo INT NOT NULL, siglas VARCHAR(3) NOT NULL, ext_id VARCHAR(255) DEFAULT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE estructura.tbn_responsabilidad (id INT NOT NULL, categoria_responsabilidad_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN NOT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1C003A0215B49E6B ON estructura.tbn_responsabilidad (categoria_responsabilidad_id)');
        $this->addSql('CREATE TABLE personal.tbn_sexo (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN NOT NULL, siglas VARCHAR(3) NOT NULL, ext_id VARCHAR(255) DEFAULT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE plan_actividades.tbn_tipo_actividad (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN NOT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE estructura.tbn_tipo_entidad (id INT NOT NULL, tipo_entidad_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN NOT NULL, color VARCHAR(50) DEFAULT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_383FF7F6FD2406C7 ON estructura.tbn_tipo_entidad (tipo_entidad_id)');
        $this->addSql('CREATE TABLE estructura.tbn_tipo_estructura (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN NOT NULL, color VARCHAR(50) DEFAULT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE personal.tbn_tipo_organizacion (id INT NOT NULL, nombre VARCHAR(255) NOT NULL, descripcion TEXT DEFAULT NULL, activo BOOLEAN NOT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE personal.tbr_persona_organizacion (id INT NOT NULL, persona_id INT NOT NULL, organizacion_id INT NOT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DC0F6D7BF5F88DB9 ON personal.tbr_persona_organizacion (persona_id)');
        $this->addSql('CREATE INDEX IDX_DC0F6D7B90B1019E ON personal.tbr_persona_organizacion (organizacion_id)');
        $this->addSql('CREATE TABLE estructura.tbr_plaza (id INT NOT NULL, estructura_id INT NOT NULL, responsabilidad_id INT NOT NULL, cantidad INT NOT NULL, creado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actualizado TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9FACD1A8CD2B7E7C ON estructura.tbr_plaza (estructura_id)');
        $this->addSql('CREATE INDEX IDX_9FACD1A896079139 ON estructura.tbr_plaza (responsabilidad_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_estructura_plaza_estructura_responsabilidad ON estructura.tbr_plaza (estructura_id, responsabilidad_id)');
        $this->addSql('ALTER TABLE plan_actividades.tbd_actividad ADD CONSTRAINT FK_616066AED347A4CA FOREIGN KEY (tipo_actividad_id) REFERENCES plan_actividades.tbn_tipo_actividad (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE plan_actividades.tbd_actividad ADD CONSTRAINT FK_616066AEB45A7D7 FOREIGN KEY (estado_actividad_id) REFERENCES plan_actividades.tbn_estado_actividad (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE plan_actividades.tbr_responsable ADD CONSTRAINT FK_316FA52FF5F88DB9 FOREIGN KEY (persona_id) REFERENCES plan_actividades.tbd_actividad (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE plan_actividades.tbr_responsable ADD CONSTRAINT FK_316FA52F6014FACA FOREIGN KEY (actividad_id) REFERENCES personal.tbd_persona (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE estructura.tbd_entidad ADD CONSTRAINT FK_AB79ADA6CD2B7E7C FOREIGN KEY (estructura_id) REFERENCES estructura.tbd_estructura (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE estructura.tbd_entidad ADD CONSTRAINT FK_AB79ADA6FD2406C7 FOREIGN KEY (tipo_entidad_id) REFERENCES estructura.tbn_tipo_entidad (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE estructura.tbd_entidad ADD CONSTRAINT FK_AB79ADA658BC1BE0 FOREIGN KEY (municipio_id) REFERENCES estructura.tbn_municipio (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE estructura.tbd_entidad ADD CONSTRAINT FK_AB79ADA64E7121AF FOREIGN KEY (provincia_id) REFERENCES estructura.tbn_provincia (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE estructura.tbd_estructura ADD CONSTRAINT FK_BF47AB85CD982D22 FOREIGN KEY (tipo_estructura_id) REFERENCES estructura.tbn_tipo_estructura (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE estructura.tbd_estructura ADD CONSTRAINT FK_BF47AB85CD2B7E7C FOREIGN KEY (estructura_id) REFERENCES estructura.tbd_estructura (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE estructura.tbd_estructura ADD CONSTRAINT FK_BF47AB854E7121AF FOREIGN KEY (provincia_id) REFERENCES estructura.tbn_provincia (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE estructura.tbd_estructura ADD CONSTRAINT FK_BF47AB8558BC1BE0 FOREIGN KEY (municipio_id) REFERENCES estructura.tbn_municipio (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE estructura.tbd_estructura ADD CONSTRAINT FK_BF47AB854498FA55 FOREIGN KEY (categoria_estructura_id) REFERENCES estructura.tbn_categoria_estructura (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE estructura.tbd_estructura ADD CONSTRAINT FK_BF47AB85DA3426AE FOREIGN KEY (nivel_id) REFERENCES estructura.tbn_nivel (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE seguridad.tbd_funcionalidad ADD CONSTRAINT FK_A7267189C07F55F5 FOREIGN KEY (modulo_id) REFERENCES seguridad.tbd_modulo (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE plan_actividades.tbd_nota ADD CONSTRAINT FK_3A6B48AC6014FACA FOREIGN KEY (actividad_id) REFERENCES plan_actividades.tbd_actividad (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personal.tbd_persona ADD CONSTRAINT FK_D817A22315ED7B6D FOREIGN KEY (datos_fuc_id) REFERENCES personal.tbd_datos_fuc (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personal.tbd_persona ADD CONSTRAINT FK_D817A2234E7121AF FOREIGN KEY (provincia_id) REFERENCES estructura.tbn_provincia (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personal.tbd_persona ADD CONSTRAINT FK_D817A22358BC1BE0 FOREIGN KEY (municipio_id) REFERENCES estructura.tbn_municipio (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personal.tbd_persona ADD CONSTRAINT FK_D817A223CF5FD27C FOREIGN KEY (clasificacion_persona_id) REFERENCES personal.tbn_clasificacion_persona (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personal.tbd_persona ADD CONSTRAINT FK_D817A2235873B5B9 FOREIGN KEY (nivel_escolar_id) REFERENCES personal.tbn_nivel_escolar (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personal.tbd_persona ADD CONSTRAINT FK_D817A22392D84F6 FOREIGN KEY (categoria_docente_id) REFERENCES personal.tbn_categoria_docente (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personal.tbd_persona ADD CONSTRAINT FK_D817A223C5AF4D0F FOREIGN KEY (profesion_id) REFERENCES personal.tbn_profesion (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personal.tbd_persona ADD CONSTRAINT FK_D817A2234683F2FA FOREIGN KEY (grado_academico_id) REFERENCES personal.tbn_grado_academico (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personal.tbd_persona ADD CONSTRAINT FK_D817A223D3ECE4BD FOREIGN KEY (categoria_investigativa_id) REFERENCES personal.tbn_categoria_investigativa (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personal.tbd_persona ADD CONSTRAINT FK_D817A223C671B40F FOREIGN KEY (carrera_id) REFERENCES personal.tbn_carrera (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personal.tbd_persona ADD CONSTRAINT FK_D817A2232B32DB58 FOREIGN KEY (sexo_id) REFERENCES personal.tbn_sexo (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personal.tbd_persona ADD CONSTRAINT FK_D817A2234498FA55 FOREIGN KEY (categoria_estructura_id) REFERENCES estructura.tbn_categoria_estructura (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personal.tbd_persona ADD CONSTRAINT FK_D817A223CD2B7E7C FOREIGN KEY (estructura_id) REFERENCES estructura.tbd_estructura (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personal.tbd_persona ADD CONSTRAINT FK_D817A22396079139 FOREIGN KEY (responsabilidad_id) REFERENCES estructura.tbn_responsabilidad (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personal.tbd_persona ADD CONSTRAINT FK_D817A223DB38439E FOREIGN KEY (usuario_id) REFERENCES seguridad.tbd_usuario (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personal.tbd_plantilla ADD CONSTRAINT FK_405B8B6CF5F88DB9 FOREIGN KEY (persona_id) REFERENCES personal.tbd_persona (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personal.tbd_plantilla ADD CONSTRAINT FK_405B8B6CCD2B7E7C FOREIGN KEY (estructura_id) REFERENCES estructura.tbd_estructura (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personal.tbd_plantilla ADD CONSTRAINT FK_405B8B6C96079139 FOREIGN KEY (responsabilidad_id) REFERENCES estructura.tbn_responsabilidad (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE seguridad.tbr_rol_funcionalidad ADD CONSTRAINT FK_5C2783B44BAB96C FOREIGN KEY (rol_id) REFERENCES seguridad.tbd_rol (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE seguridad.tbr_rol_funcionalidad ADD CONSTRAINT FK_5C2783B43637E16E FOREIGN KEY (funcionalidad_id) REFERENCES seguridad.tbd_funcionalidad (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE plan_actividades.tbd_todo_lista ADD CONSTRAINT FK_AE298B7FDB38439E FOREIGN KEY (usuario_id) REFERENCES seguridad.tbd_usuario (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE seguridad.tbd_usuario ADD CONSTRAINT FK_17879B6F5F88DB9 FOREIGN KEY (persona_id) REFERENCES personal.tbd_persona (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE seguridad.tbr_user_rol ADD CONSTRAINT FK_F808892AA76ED395 FOREIGN KEY (user_id) REFERENCES seguridad.tbd_usuario (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE seguridad.tbr_user_rol ADD CONSTRAINT FK_F808892A4BAB96C FOREIGN KEY (rol_id) REFERENCES seguridad.tbd_rol (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE estructura.tbn_categoria_responsabilidad ADD CONSTRAINT FK_39E2253E15B49E6B FOREIGN KEY (categoria_responsabilidad_id) REFERENCES estructura.tbn_categoria_responsabilidad (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE estructura.tbn_municipio ADD CONSTRAINT FK_AF623AA94E7121AF FOREIGN KEY (provincia_id) REFERENCES estructura.tbn_provincia (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personal.tbn_organizacion ADD CONSTRAINT FK_7DDAD16046EB71B9 FOREIGN KEY (tipo_organizacion_id) REFERENCES personal.tbn_tipo_organizacion (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE estructura.tbn_responsabilidad ADD CONSTRAINT FK_1C003A0215B49E6B FOREIGN KEY (categoria_responsabilidad_id) REFERENCES estructura.tbn_categoria_responsabilidad (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE estructura.tbn_tipo_entidad ADD CONSTRAINT FK_383FF7F6FD2406C7 FOREIGN KEY (tipo_entidad_id) REFERENCES estructura.tbn_tipo_entidad (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personal.tbr_persona_organizacion ADD CONSTRAINT FK_DC0F6D7BF5F88DB9 FOREIGN KEY (persona_id) REFERENCES personal.tbd_persona (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personal.tbr_persona_organizacion ADD CONSTRAINT FK_DC0F6D7B90B1019E FOREIGN KEY (organizacion_id) REFERENCES personal.tbn_organizacion (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE estructura.tbr_plaza ADD CONSTRAINT FK_9FACD1A8CD2B7E7C FOREIGN KEY (estructura_id) REFERENCES estructura.tbd_estructura (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE estructura.tbr_plaza ADD CONSTRAINT FK_9FACD1A896079139 FOREIGN KEY (responsabilidad_id) REFERENCES estructura.tbn_responsabilidad (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE plan_actividades.tbr_responsable DROP CONSTRAINT FK_316FA52FF5F88DB9');
        $this->addSql('ALTER TABLE plan_actividades.tbd_nota DROP CONSTRAINT FK_3A6B48AC6014FACA');
        $this->addSql('ALTER TABLE personal.tbd_persona DROP CONSTRAINT FK_D817A22315ED7B6D');
        $this->addSql('ALTER TABLE estructura.tbd_entidad DROP CONSTRAINT FK_AB79ADA6CD2B7E7C');
        $this->addSql('ALTER TABLE estructura.tbd_estructura DROP CONSTRAINT FK_BF47AB85CD2B7E7C');
        $this->addSql('ALTER TABLE personal.tbd_persona DROP CONSTRAINT FK_D817A223CD2B7E7C');
        $this->addSql('ALTER TABLE personal.tbd_plantilla DROP CONSTRAINT FK_405B8B6CCD2B7E7C');
        $this->addSql('ALTER TABLE estructura.tbr_plaza DROP CONSTRAINT FK_9FACD1A8CD2B7E7C');
        $this->addSql('ALTER TABLE seguridad.tbr_rol_funcionalidad DROP CONSTRAINT FK_5C2783B43637E16E');
        $this->addSql('ALTER TABLE seguridad.tbd_funcionalidad DROP CONSTRAINT FK_A7267189C07F55F5');
        $this->addSql('ALTER TABLE plan_actividades.tbr_responsable DROP CONSTRAINT FK_316FA52F6014FACA');
        $this->addSql('ALTER TABLE personal.tbd_plantilla DROP CONSTRAINT FK_405B8B6CF5F88DB9');
        $this->addSql('ALTER TABLE seguridad.tbd_usuario DROP CONSTRAINT FK_17879B6F5F88DB9');
        $this->addSql('ALTER TABLE personal.tbr_persona_organizacion DROP CONSTRAINT FK_DC0F6D7BF5F88DB9');
        $this->addSql('ALTER TABLE seguridad.tbr_rol_funcionalidad DROP CONSTRAINT FK_5C2783B44BAB96C');
        $this->addSql('ALTER TABLE seguridad.tbr_user_rol DROP CONSTRAINT FK_F808892A4BAB96C');
        $this->addSql('ALTER TABLE personal.tbd_persona DROP CONSTRAINT FK_D817A223DB38439E');
        $this->addSql('ALTER TABLE plan_actividades.tbd_todo_lista DROP CONSTRAINT FK_AE298B7FDB38439E');
        $this->addSql('ALTER TABLE seguridad.tbr_user_rol DROP CONSTRAINT FK_F808892AA76ED395');
        $this->addSql('ALTER TABLE personal.tbd_persona DROP CONSTRAINT FK_D817A223C671B40F');
        $this->addSql('ALTER TABLE personal.tbd_persona DROP CONSTRAINT FK_D817A22392D84F6');
        $this->addSql('ALTER TABLE estructura.tbd_estructura DROP CONSTRAINT FK_BF47AB854498FA55');
        $this->addSql('ALTER TABLE personal.tbd_persona DROP CONSTRAINT FK_D817A2234498FA55');
        $this->addSql('ALTER TABLE personal.tbd_persona DROP CONSTRAINT FK_D817A223D3ECE4BD');
        $this->addSql('ALTER TABLE estructura.tbn_categoria_responsabilidad DROP CONSTRAINT FK_39E2253E15B49E6B');
        $this->addSql('ALTER TABLE estructura.tbn_responsabilidad DROP CONSTRAINT FK_1C003A0215B49E6B');
        $this->addSql('ALTER TABLE personal.tbd_persona DROP CONSTRAINT FK_D817A223CF5FD27C');
        $this->addSql('ALTER TABLE plan_actividades.tbd_actividad DROP CONSTRAINT FK_616066AEB45A7D7');
        $this->addSql('ALTER TABLE personal.tbd_persona DROP CONSTRAINT FK_D817A2234683F2FA');
        $this->addSql('ALTER TABLE estructura.tbd_entidad DROP CONSTRAINT FK_AB79ADA658BC1BE0');
        $this->addSql('ALTER TABLE estructura.tbd_estructura DROP CONSTRAINT FK_BF47AB8558BC1BE0');
        $this->addSql('ALTER TABLE personal.tbd_persona DROP CONSTRAINT FK_D817A22358BC1BE0');
        $this->addSql('ALTER TABLE estructura.tbd_estructura DROP CONSTRAINT FK_BF47AB85DA3426AE');
        $this->addSql('ALTER TABLE personal.tbd_persona DROP CONSTRAINT FK_D817A2235873B5B9');
        $this->addSql('ALTER TABLE personal.tbr_persona_organizacion DROP CONSTRAINT FK_DC0F6D7B90B1019E');
        $this->addSql('ALTER TABLE personal.tbd_persona DROP CONSTRAINT FK_D817A223C5AF4D0F');
        $this->addSql('ALTER TABLE estructura.tbd_entidad DROP CONSTRAINT FK_AB79ADA64E7121AF');
        $this->addSql('ALTER TABLE estructura.tbd_estructura DROP CONSTRAINT FK_BF47AB854E7121AF');
        $this->addSql('ALTER TABLE personal.tbd_persona DROP CONSTRAINT FK_D817A2234E7121AF');
        $this->addSql('ALTER TABLE estructura.tbn_municipio DROP CONSTRAINT FK_AF623AA94E7121AF');
        $this->addSql('ALTER TABLE personal.tbd_persona DROP CONSTRAINT FK_D817A22396079139');
        $this->addSql('ALTER TABLE personal.tbd_plantilla DROP CONSTRAINT FK_405B8B6C96079139');
        $this->addSql('ALTER TABLE estructura.tbr_plaza DROP CONSTRAINT FK_9FACD1A896079139');
        $this->addSql('ALTER TABLE personal.tbd_persona DROP CONSTRAINT FK_D817A2232B32DB58');
        $this->addSql('ALTER TABLE plan_actividades.tbd_actividad DROP CONSTRAINT FK_616066AED347A4CA');
        $this->addSql('ALTER TABLE estructura.tbd_entidad DROP CONSTRAINT FK_AB79ADA6FD2406C7');
        $this->addSql('ALTER TABLE estructura.tbn_tipo_entidad DROP CONSTRAINT FK_383FF7F6FD2406C7');
        $this->addSql('ALTER TABLE estructura.tbd_estructura DROP CONSTRAINT FK_BF47AB85CD982D22');
        $this->addSql('ALTER TABLE personal.tbn_organizacion DROP CONSTRAINT FK_7DDAD16046EB71B9');
        $this->addSql('DROP SEQUENCE planificacion.plan_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE plan_actividades.tbd_actividad_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE personal.tbd_datos_fuc_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE estructura.tbd_entidad_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE estructura.tbd_estructura_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE seguridad.tbd_funcionalidad_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE seguridad.tbd_modulo_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE plan_actividades.tbd_nota_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE personal.tbd_persona_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE personal.tbd_plantilla_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE seguridad.tbd_rol_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE plan_actividades.tbd_todo_lista_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE seguridad.tbd_usuario_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE personal.tbn_carrera_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE personal.tbn_categoria_docente_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE estructura.tbn_categoria_estructura_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE personal.tbn_categoria_investigativa_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE estructura.tbn_categoria_responsabilidad_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE personal.tbn_clasificacion_persona_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE plan_actividades.tbn_estado_actividad_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE personal.tbn_grado_academico_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE estructura.tbn_municipio_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE estructura.tbn_nivel_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE personal.tbn_nivel_escolar_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE personal.tbn_organizacion_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE personal.tbn_profesion_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE estructura.tbn_provincia_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE estructura.tbn_responsabilidad_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE personal.tbn_sexo_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE plan_actividades.tbn_tipo_actividad_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE estructura.tbn_tipo_entidad_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE estructura.tbn_tipo_estructura_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE personal.tbn_tipo_organizacion_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE personal.tbr_persona_organizacion_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE estructura.tbr_plaza_id_seq CASCADE');
        $this->addSql('DROP TABLE planificacion.plan');
        $this->addSql('DROP TABLE plan_actividades.tbd_actividad');
        $this->addSql('DROP TABLE plan_actividades.tbr_responsable');
        $this->addSql('DROP TABLE personal.tbd_datos_fuc');
        $this->addSql('DROP TABLE estructura.tbd_entidad');
        $this->addSql('DROP TABLE estructura.tbd_estructura');
        $this->addSql('DROP TABLE seguridad.tbd_funcionalidad');
        $this->addSql('DROP TABLE seguridad.tbd_modulo');
        $this->addSql('DROP TABLE plan_actividades.tbd_nota');
        $this->addSql('DROP TABLE personal.tbd_persona');
        $this->addSql('DROP TABLE personal.tbd_plantilla');
        $this->addSql('DROP TABLE seguridad.tbd_rol');
        $this->addSql('DROP TABLE seguridad.tbr_rol_funcionalidad');
        $this->addSql('DROP TABLE plan_actividades.tbd_todo_lista');
        $this->addSql('DROP TABLE seguridad.tbd_usuario');
        $this->addSql('DROP TABLE seguridad.tbr_user_rol');
        $this->addSql('DROP TABLE personal.tbn_carrera');
        $this->addSql('DROP TABLE personal.tbn_categoria_docente');
        $this->addSql('DROP TABLE estructura.tbn_categoria_estructura');
        $this->addSql('DROP TABLE personal.tbn_categoria_investigativa');
        $this->addSql('DROP TABLE estructura.tbn_categoria_responsabilidad');
        $this->addSql('DROP TABLE personal.tbn_clasificacion_persona');
        $this->addSql('DROP TABLE plan_actividades.tbn_estado_actividad');
        $this->addSql('DROP TABLE personal.tbn_grado_academico');
        $this->addSql('DROP TABLE estructura.tbn_municipio');
        $this->addSql('DROP TABLE estructura.tbn_nivel');
        $this->addSql('DROP TABLE personal.tbn_nivel_escolar');
        $this->addSql('DROP TABLE personal.tbn_organizacion');
        $this->addSql('DROP TABLE personal.tbn_profesion');
        $this->addSql('DROP TABLE estructura.tbn_provincia');
        $this->addSql('DROP TABLE estructura.tbn_responsabilidad');
        $this->addSql('DROP TABLE personal.tbn_sexo');
        $this->addSql('DROP TABLE plan_actividades.tbn_tipo_actividad');
        $this->addSql('DROP TABLE estructura.tbn_tipo_entidad');
        $this->addSql('DROP TABLE estructura.tbn_tipo_estructura');
        $this->addSql('DROP TABLE personal.tbn_tipo_organizacion');
        $this->addSql('DROP TABLE personal.tbr_persona_organizacion');
        $this->addSql('DROP TABLE estructura.tbr_plaza');
    }
}
